name: equatable_lint_example
description: Package with every examples for the equatable_lint package
version: 0.1.3

publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ">=6.4.1 <8.0.0"
  equatable: ">=2.0.5 <3.0.0"

dev_dependencies:
  custom_lint: ">=0.6.4 <0.8.0"
  equatable_lint:
    path: ../
