name: equatable_lint_example
description: Package with every examples for the equatable_lint package
version: 0.1.3

publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ">=7.5.0 <9.0.0"
  equatable: ">=2.0.5 <3.0.0"

dev_dependencies:
  custom_lint: ">=0.7.5 <0.9.0"
  equatable_lint:
    path: ../
